import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "useAnimatedText",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-gray-800">
      <head>
        <meta name="color-scheme" content="dark" />
      </head>
      <body
        className={`${inter.className} dark relative flex h-full flex-col text-gray-200 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
